MB-59116: Rebuild gcc13 with default dwarf version 4
Change-Id: Ibc9ddf4005fe6c0d2267c0c4ac4b6d9ff4090f29
Reviewed-on: https://review.couchbase.org/c/build-infra/+/201421
Tested-by: Blair Watt <blair.watt@couchbase.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>

diff --git a/docker/compile/gcc/single/Dockerfile b/docker/compile/gcc/single/Dockerfile
--- a/docker/compile/gcc/single/Dockerfile
+++ b/docker/compile/gcc/single/Dockerfile
@@ -37,6 +37,13 @@ RUN set -x \
 RUN cd /tmp/deploy/gcc-${GCC_VER} && ./contrib/download_prerequisites
 RUN mkdir /tmp/deploy/objdir
 WORKDIR /tmp/deploy/objdir
+RUN set -x \
+    && sed 's/#define DWARF_VERSION_DEFAULT 5/#define DWARF_VERSION_DEFAULT 4/' /tmp/deploy/gcc-${GCC_VER}/gcc/defaults.h > /tmp/defaults.h.fixed \
+    && if cmp -s /tmp/deploy/gcc-${GCC_VER}/gcc/defaults.h /tmp/defaults.h.fixed; then \
+      echo "Couldn't set DWARF_VERSION_DEFAULT" && exit 1; \
+    else \
+      mv /tmp/defaults.h.fixed /tmp/deploy/gcc-${GCC_VER}/gcc/defaults.h; \
+    fi
 RUN $PWD/../gcc-${GCC_VER}/configure \
       --prefix=/opt/gcc-${GCC_VER} \
       --disable-multilib \
