CBD-5588: Add couchbase-cloud-native-gateway to rhcc metadata CBD-5589: Add buildx plugin to single linux image           Add awscli to single linux image           Create `ninja` symlink to `ninja-build`           Make sidecar builds optional
Change-Id: I9a642a0fbac745874bc90a2b678eeebefaf68a34
Reviewed-on: https://review.couchbase.org/c/build-infra/+/196001
Reviewed-by: Chris Hillery <ceej@couchbase.com>
Tested-by: Blair Watt <blair.watt@couchbase.com>

diff --git a/docker/buildslaves/couchbase-server/single/go b/docker/buildslaves/couchbase-server/single/go
--- a/docker/buildslaves/couchbase-server/single/go
+++ b/docker/buildslaves/couchbase-server/single/go
@@ -1,4 +1,4 @@
-#!/bin/sh -ex
+#!/bin/sh -e
 
 # Things you might want to adjust:
 IMAGE=couchbasebuild/server-linux-build
@@ -16,8 +16,33 @@ cp -a ../../util/healthcheck.sh build
 
 TAG=$(date +%Y%m%d)
 
-if [ "$1" = "--publish" ]
-then
+PUBLISH=false
+SIDECARS=false
+
+usage() {
+  echo "Usage: $0 [--publish] [--sidecars]"
+  echo "Options:"
+  echo "  --publish    Publish the image to docker hub"
+  echo "  --sidecars   Build and publish sidecars"
+}
+
+for arg in "$@"; do
+  case "${arg}" in
+    --publish)
+      PUBLISH=true
+      ;;
+    --sidecars)
+      SIDECARS=true
+      ;;
+    *)
+      echo "Invalid flag: ${arg}"
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+if ${PUBLISHING}; then
   BUILDX=buildx
   ACTION=--push
   PLATFORMS=linux/amd64,linux/arm64
@@ -71,8 +96,7 @@ docker ${BUILDX} build --pull ${ACTION} \
   --build-arg YQ_VER=${YQ} \
   .
 
-if [ "$1" = "--publish" ]
-then
+if ${SIDECARS}; then
   # Also ensure the sidecars are updated appropriately
   for pkg_type in deb rpm
   do
